param(
    [string]$Notes = '앱 내 새 버전 알림, 릴리즈 페이지 보기와 사용자 승인 후 업데이트 설치를 추가했습니다.'
)

$ErrorActionPreference = 'Stop'
function Get-ReleaseFileHash([string]$Path) {
    $stream = [IO.File]::OpenRead($Path)
    $hasher = [Security.Cryptography.SHA256]::Create()
    try { return [BitConverter]::ToString($hasher.ComputeHash($stream)).Replace('-', '') }
    finally {
        $hasher.Dispose()
        $stream.Dispose()
    }
}

$projectRoot = Split-Path -Parent $PSScriptRoot
$packageVersion = [string](Get-Content -LiteralPath (Join-Path $projectRoot 'package.json') -Raw | ConvertFrom-Json).version
$configuration = Get-Content -LiteralPath (Join-Path $projectRoot 'src-tauri/tauri.conf.json') -Raw | ConvertFrom-Json
$cargoContents = Get-Content -LiteralPath (Join-Path $projectRoot 'src-tauri/Cargo.toml') -Raw
$cargoPackage = [regex]::Match($cargoContents, '(?ms)^\[package\]\s*(?<body>.*?)(?=^\[|\z)').Groups['body'].Value
$cargoVersion = [regex]::Match($cargoPackage, '(?m)^version\s*=\s*"(?<version>[^"]+)"').Groups['version'].Value
if ($packageVersion -notmatch '^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?(?:\+[0-9A-Za-z.-]+)?$' -or $packageVersion -ne $configuration.version -or $packageVersion -ne $cargoVersion) {
    throw 'package.json, src-tauri/Cargo.toml, and src-tauri/tauri.conf.json must use the same valid release version.'
}
if ($configuration.bundle.createUpdaterArtifacts -ne $true -or $configuration.plugins.updater.requireSignedVersion -ne $true) {
    throw 'Packaging requires updater artifacts with signatures bound to the app version.'
}

$binary = Join-Path $projectRoot 'src-tauri/target/release/ai-token.exe'
$installerName = [string]$configuration.productName + '_' + $packageVersion + '_x64-setup.exe'
$installer = Join-Path $projectRoot ('src-tauri/target/release/bundle/nsis/' + $installerName)
$installerSignature = $installer + '.sig'
foreach ($requiredFile in @($binary, $installer, $installerSignature, (Join-Path $projectRoot 'BRAND_ASSETS.md'), (Join-Path $projectRoot 'LICENSE'))) {
    if (-not (Test-Path -LiteralPath $requiredFile -PathType Leaf)) {
        throw "Release input missing: $requiredFile. Run npm run build:desktop first."
    }
}

# Select only this version's x64 installer, then verify the signature's version field.
# The updater performs the cryptographic signature verification when downloading.
$signature = (Get-Content -LiteralPath $installerSignature -Raw).Trim()
try { $signatureText = [Text.Encoding]::UTF8.GetString([Convert]::FromBase64String($signature)) }
catch { throw 'The installer signature is not a valid Tauri signature.' }
$trustedComment = [regex]::Match($signatureText, '(?m)^trusted comment: (?<comment>[^\r\n]+)').Groups['comment'].Value
$signedVersion = [regex]::Match($trustedComment, '(?:^|\t)version:(?<version>[^\t\r\n]+)(?:\t|$)').Groups['version'].Value
if ($signedVersion -ne $packageVersion) {
    throw 'The installer signature must be generated by tauri build for this exact app version. Do not reuse a previous version signature.'
}
$binaryVersion = (Get-Item -LiteralPath $binary).VersionInfo.ProductVersion
if ($binaryVersion -ne $packageVersion) {
    throw "Release executable version '$binaryVersion' does not match $packageVersion. Rebuild the desktop app."
}

$archiveStem = 'AI-Token-' + $packageVersion + '-windows-x64'
$releaseRoot = Join-Path $projectRoot 'release'
$packageRoot = Join-Path $releaseRoot $archiveStem
New-Item -ItemType Directory -Path $packageRoot -Force | Out-Null
$outputBinary = Join-Path $packageRoot 'ai-token.exe'
$readmePath = Join-Path $packageRoot 'README.txt'
$brandsPath = Join-Path $packageRoot 'BRAND_ASSETS.md'
$licensePath = Join-Path $packageRoot 'LICENSE'
$sourceHash = Get-ReleaseFileHash $binary
$destinationUnchanged = (Test-Path -LiteralPath $outputBinary -PathType Leaf) -and (Get-ReleaseFileHash $outputBinary) -eq $sourceHash
if (-not $destinationUnchanged) {
    try { Copy-Item -LiteralPath $binary -Destination $outputBinary -Force }
    catch {
        throw "Cannot replace $outputBinary. Close AI Token running from the release folder, then run scripts/package-release.ps1 again. $($_.Exception.Message)"
    }
}
Copy-Item -LiteralPath (Join-Path $projectRoot 'BRAND_ASSETS.md') -Destination $brandsPath -Force
Copy-Item -LiteralPath (Join-Path $projectRoot 'LICENSE') -Destination $licensePath -Force

$readme = @"
AI Token $packageVersion - Windows x64

자동 업데이트를 사용하려면 함께 배포된 AI-Token-$packageVersion-windows-x64-setup.exe로 설치하세요.
기존 0.1.0 사용자는 앱을 종료하고 이 설치 파일을 한 번 직접 실행해야 합니다.
새 버전 알림에서 '릴리즈 페이지 보기'로 직접 다운로드하거나 '업데이트 설치'를 선택할 수 있습니다.
'승인하고 설치'를 눌러야 파일 다운로드, 서명 검증과 설치를 시작합니다.
포터블 ZIP은 압축 해제 후 실행할 수 있지만 자동 업데이트에는 설치형을 사용하세요.

1. ZIP을 원하는 폴더에 압축 해제합니다.
2. ai-token.exe를 실행합니다.
3. 작업표시줄 오른쪽 AI Token 아이콘을 클릭하면 상세 창이 열립니다.
4. 설정에서 미니바에 표시할 AI를 선택합니다.
5. 트레이 아이콘 우클릭 메뉴에서 종료합니다.

환경: Windows 10/11 x64, Microsoft Edge WebView2 Runtime.
WebView2: https://developer.microsoft.com/microsoft-edge/webview2/

Codex: 이 PC에 설치되고 로그인된 Codex CLI가 필요합니다.
Claude Code: 앱 설정의 '이 PC용 명령'으로 별도 연결합니다.
Antigravity/Grok: 아직 한도 조회를 지원하지 않습니다.

잔여값은 구독 한도의 비율이며, 정확한 잔여 토큰 수가 아닙니다.
Codex는 기본 5분마다 조회합니다. Claude는 연결된 상태줄의 입력에 따라 갱신합니다.
설정은 해당 PC의 앱 데이터 폴더에 저장됩니다.
ZIP에는 개인 설정이나 로그인 인증 정보를 포함하지 않습니다.

AI Token은 각 AI 서비스와 제휴하지 않은 독립 앱입니다.
서비스 아이콘의 출처는 BRAND_ASSETS.md, 앱 라이선스는 LICENSE를 확인하세요.
"@
$utf8 = New-Object Text.UTF8Encoding($false)
[IO.File]::WriteAllText($readmePath, $readme, $utf8)

$archivePath = Join-Path $releaseRoot ($archiveStem + '.zip')
# Zip the fresh build input; an identical EXE may still be running from the portable output folder.
Compress-Archive -LiteralPath @($binary, $readmePath, $brandsPath, $licensePath) -DestinationPath $archivePath -Force

$outputInstallerName = $archiveStem + '-setup.exe'
$outputInstaller = Join-Path $releaseRoot $outputInstallerName
$outputSignature = $outputInstaller + '.sig'
Copy-Item -LiteralPath $installer -Destination $outputInstaller -Force
Copy-Item -LiteralPath $installerSignature -Destination $outputSignature -Force

$manifest = [ordered]@{
    version = $packageVersion
    notes = $Notes
    pub_date = [DateTimeOffset]::UtcNow.ToString('yyyy-MM-ddTHH:mm:ssZ')
    platforms = [ordered]@{
        'windows-x86_64' = [ordered]@{
            url = 'https://github.com/xinun/AI-token-monitoring/releases/download/v' + $packageVersion + '/' + $outputInstallerName
            signature = $signature
        }
    }
}
$manifestPath = Join-Path $releaseRoot 'latest.json'
[IO.File]::WriteAllText($manifestPath, ($manifest | ConvertTo-Json -Depth 6), $utf8)

Get-Item -LiteralPath $outputInstaller, $outputSignature, $manifestPath, $archivePath | Select-Object FullName, Length
